# Auto-generated by oxyde generate-stubs
# DO NOT EDIT - This file will be overwritten

from typing import Any, Literal
from datetime import datetime, date, time
from decimal import Decimal
from uuid import UUID

from oxyde import OxydeModel
from oxyde.queries import Query, QueryManager


class User(OxydeModel):
    class Meta:
        is_table: bool
        table_name: str
    id: int | None
    username: str
    email: str
    created_at: datetime | None
    objects: "UserManager"

class Tag(OxydeModel):
    class Meta:
        is_table: bool
        table_name: str
    id: int | None
    name: str
    slug: str
    objects: "TagManager"

class Post(OxydeModel):
    class Meta:
        is_table: bool
        table_name: str
    id: int | None
    title: str
    content: str
    published: bool
    created_at: datetime | None
    updated_at: datetime | None
    author: User | None
    author_id: int | None
    objects: "PostManager"

class Comment(OxydeModel):
    class Meta:
        is_table: bool
        table_name: str
    id: int | None
    content: str
    created_at: datetime | None
    post: Post | None
    author: User | None
    post_id: int | None
    author_id: int | None
    objects: "CommentManager"

class PostTag(OxydeModel):
    class Meta:
        is_table: bool
        table_name: str
    id: int | None
    post: Post | None
    tag: Tag | None
    post_id: int | None
    tag_id: int | None
    objects: "PostTagManager"


class UserQuery(Query[User]):
    """Type-safe Query for User model."""

    # Query building methods (sync, return Query)

    def filter(
        self,
        *args: Any,
        created_at: datetime | None = None,
        created_at__gt: datetime | None = None,
        created_at__gte: datetime | None = None,
        created_at__lt: datetime | None = None,
        created_at__lte: datetime | None = None,
        created_at__between: tuple[datetime, datetime] | None = None,
        created_at__range: datetime | None = None,
        created_at__year: int | None = None,
        created_at__month: int | None = None,
        created_at__day: int | None = None,
        created_at__in: list[datetime] | None = None,
        created_at__isnull: bool | None = None,
        email: str | None = None,
        email__contains: str | None = None,
        email__icontains: str | None = None,
        email__startswith: str | None = None,
        email__istartswith: str | None = None,
        email__endswith: str | None = None,
        email__iendswith: str | None = None,
        email__iexact: str | None = None,
        email__in: list[str] | None = None,
        email__isnull: bool | None = None,
        id: int | None = None,
        id__gt: int | None = None,
        id__gte: int | None = None,
        id__lt: int | None = None,
        id__lte: int | None = None,
        id__between: tuple[int, int] | None = None,
        id__range: int | None = None,
        id__in: list[int] | None = None,
        id__isnull: bool | None = None,
        username: str | None = None,
        username__contains: str | None = None,
        username__icontains: str | None = None,
        username__startswith: str | None = None,
        username__istartswith: str | None = None,
        username__endswith: str | None = None,
        username__iendswith: str | None = None,
        username__iexact: str | None = None,
        username__in: list[str] | None = None,
        username__isnull: bool | None = None,
    ) -> "UserQuery":
        """Filter by Q-expressions or field lookups."""
        ...

    def exclude(
        self,
        *args: Any,
        created_at: datetime | None = None,
        created_at__gt: datetime | None = None,
        created_at__gte: datetime | None = None,
        created_at__lt: datetime | None = None,
        created_at__lte: datetime | None = None,
        created_at__between: tuple[datetime, datetime] | None = None,
        created_at__range: datetime | None = None,
        created_at__year: int | None = None,
        created_at__month: int | None = None,
        created_at__day: int | None = None,
        created_at__in: list[datetime] | None = None,
        created_at__isnull: bool | None = None,
        email: str | None = None,
        email__contains: str | None = None,
        email__icontains: str | None = None,
        email__startswith: str | None = None,
        email__istartswith: str | None = None,
        email__endswith: str | None = None,
        email__iendswith: str | None = None,
        email__iexact: str | None = None,
        email__in: list[str] | None = None,
        email__isnull: bool | None = None,
        id: int | None = None,
        id__gt: int | None = None,
        id__gte: int | None = None,
        id__lt: int | None = None,
        id__lte: int | None = None,
        id__between: tuple[int, int] | None = None,
        id__range: int | None = None,
        id__in: list[int] | None = None,
        id__isnull: bool | None = None,
        username: str | None = None,
        username__contains: str | None = None,
        username__icontains: str | None = None,
        username__startswith: str | None = None,
        username__istartswith: str | None = None,
        username__endswith: str | None = None,
        username__iendswith: str | None = None,
        username__iexact: str | None = None,
        username__in: list[str] | None = None,
        username__isnull: bool | None = None,
    ) -> "UserQuery":
        """Exclude objects matching field lookups."""
        ...

    def order_by(self, *fields: Literal["created_at", "-created_at", "email", "-email", "id", "-id", "username", "-username"]) -> "UserQuery":
        """Order results by fields."""
        ...

    def limit(self, n: int) -> "UserQuery":
        """Limit number of results."""
        ...

    def offset(self, n: int) -> "UserQuery":
        """Skip first n results."""
        ...

    def distinct(self, value: bool = True) -> "UserQuery":
        """Return distinct results."""
        ...

    def select(self, *fields: Literal["created_at", "email", "id", "username"]) -> "UserQuery":
        """Select specific fields."""
        ...

    def join(self, *paths: str) -> "UserQuery":
        """Perform LEFT JOIN for relations."""
        ...

    def prefetch(self, *paths: str) -> "UserQuery":
        """Prefetch related objects (separate queries)."""
        ...

    def for_update(self) -> "UserQuery":
        """Add FOR UPDATE lock to query."""
        ...

    def for_share(self) -> "UserQuery":
        """Add FOR SHARE lock to query."""
        ...

    def annotate(self, **annotations: Any) -> "UserQuery":
        """Add computed fields using aggregate functions."""
        ...

    def group_by(self, *fields: Literal["created_at", "email", "id", "username"]) -> "UserQuery":
        """Add GROUP BY clause."""
        ...

    def having(self, *q_exprs: Any, **kwargs: Any) -> "UserQuery":
        """Add HAVING clause for filtering grouped results."""
        ...

    def values(self, *fields: Literal["created_at", "email", "id", "username"]) -> "UserQuery":
        """Return dicts instead of models."""
        ...

    def values_list(self, *fields: Literal["created_at", "email", "id", "username"], flat: bool = False) -> "UserQuery":
        """Return tuples/values instead of models."""
        ...

    # Terminal methods (async, execute query)

    async def all(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> list[User]:
        """Execute query and return all results."""
        ...

    async def first(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> User | None:
        """Execute query and return first result."""
        ...

    async def last(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> User | None:
        """Execute query and return last result."""
        ...

    async def count(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Count matching objects."""
        ...

    async def sum(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate sum of field values."""
        ...

    async def avg(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate average of field values."""
        ...

    async def max(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get maximum field value."""
        ...

    async def min(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get minimum field value."""
        ...

    async def update(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **values: Any,
    ) -> int:
        """Update matching objects."""
        ...

    async def increment(
        self,
        field: str,
        by: int | float = 1,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Atomically increment a field value."""
        ...

    async def delete(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Delete matching objects."""
        ...

class UserManager(QueryManager[User]):
    """Type-safe Manager for User model."""

    # Query building methods (sync, return Query)

    def query(self) -> UserQuery:
        """Return a Query builder for this model."""
        ...

    def filter(
        self,
        *args: Any,
        created_at: datetime | None = None,
        created_at__gt: datetime | None = None,
        created_at__gte: datetime | None = None,
        created_at__lt: datetime | None = None,
        created_at__lte: datetime | None = None,
        created_at__between: tuple[datetime, datetime] | None = None,
        created_at__range: datetime | None = None,
        created_at__year: int | None = None,
        created_at__month: int | None = None,
        created_at__day: int | None = None,
        created_at__in: list[datetime] | None = None,
        created_at__isnull: bool | None = None,
        email: str | None = None,
        email__contains: str | None = None,
        email__icontains: str | None = None,
        email__startswith: str | None = None,
        email__istartswith: str | None = None,
        email__endswith: str | None = None,
        email__iendswith: str | None = None,
        email__iexact: str | None = None,
        email__in: list[str] | None = None,
        email__isnull: bool | None = None,
        id: int | None = None,
        id__gt: int | None = None,
        id__gte: int | None = None,
        id__lt: int | None = None,
        id__lte: int | None = None,
        id__between: tuple[int, int] | None = None,
        id__range: int | None = None,
        id__in: list[int] | None = None,
        id__isnull: bool | None = None,
        username: str | None = None,
        username__contains: str | None = None,
        username__icontains: str | None = None,
        username__startswith: str | None = None,
        username__istartswith: str | None = None,
        username__endswith: str | None = None,
        username__iendswith: str | None = None,
        username__iexact: str | None = None,
        username__in: list[str] | None = None,
        username__isnull: bool | None = None,
    ) -> UserQuery:
        """Filter by Q-expressions or field lookups."""
        ...

    def exclude(
        self,
        *args: Any,
        created_at: datetime | None = None,
        created_at__gt: datetime | None = None,
        created_at__gte: datetime | None = None,
        created_at__lt: datetime | None = None,
        created_at__lte: datetime | None = None,
        created_at__between: tuple[datetime, datetime] | None = None,
        created_at__range: datetime | None = None,
        created_at__year: int | None = None,
        created_at__month: int | None = None,
        created_at__day: int | None = None,
        created_at__in: list[datetime] | None = None,
        created_at__isnull: bool | None = None,
        email: str | None = None,
        email__contains: str | None = None,
        email__icontains: str | None = None,
        email__startswith: str | None = None,
        email__istartswith: str | None = None,
        email__endswith: str | None = None,
        email__iendswith: str | None = None,
        email__iexact: str | None = None,
        email__in: list[str] | None = None,
        email__isnull: bool | None = None,
        id: int | None = None,
        id__gt: int | None = None,
        id__gte: int | None = None,
        id__lt: int | None = None,
        id__lte: int | None = None,
        id__between: tuple[int, int] | None = None,
        id__range: int | None = None,
        id__in: list[int] | None = None,
        id__isnull: bool | None = None,
        username: str | None = None,
        username__contains: str | None = None,
        username__icontains: str | None = None,
        username__startswith: str | None = None,
        username__istartswith: str | None = None,
        username__endswith: str | None = None,
        username__iendswith: str | None = None,
        username__iexact: str | None = None,
        username__in: list[str] | None = None,
        username__isnull: bool | None = None,
    ) -> UserQuery:
        """Exclude objects matching field lookups."""
        ...

    def values(self, *fields: Literal["created_at", "email", "id", "username"]) -> UserQuery:
        """Return dicts instead of models."""
        ...

    def values_list(self, *fields: Literal["created_at", "email", "id", "username"], flat: bool = False) -> UserQuery:
        """Return tuples/values instead of models."""
        ...

    def distinct(self, distinct: bool = True) -> UserQuery:
        """Return distinct results."""
        ...

    def join(self, *paths: str) -> UserQuery:
        """Perform LEFT JOIN for relations."""
        ...

    def prefetch(self, *paths: str) -> UserQuery:
        """Prefetch related objects (separate queries)."""
        ...

    def for_update(self) -> UserQuery:
        """Add FOR UPDATE lock to query."""
        ...

    def for_share(self) -> UserQuery:
        """Add FOR SHARE lock to query."""
        ...

    # Terminal methods (async, execute query)

    async def get(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> User:
        """Get single object matching lookups."""
        ...

    async def get_or_none(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> User | None:
        """Get object or None if not found."""
        ...

    async def get_or_create(
        self,
        *,
        defaults: dict[str, Any] | None = None,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> tuple[User, bool]:
        """Get object or create if not found. Returns (object, created)."""
        ...

    async def all(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        mode: str = "models",
    ) -> list[User]:
        """Get all objects."""
        ...

    async def first(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> User | None:
        """Get first object."""
        ...

    async def last(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> User | None:
        """Get last object."""
        ...

    async def count(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Count all objects."""
        ...

    async def sum(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate sum of field values."""
        ...

    async def avg(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate average of field values."""
        ...

    async def max(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get maximum field value."""
        ...

    async def min(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get minimum field value."""
        ...

    async def create(
        self,
        *,
        instance: User | None = None,
        client: Any | None = None,
        using: str | None = None,
        created_at: datetime | None = None,
        email: str | None = None,
        id: int | None = None,
        username: str | None = None,
    ) -> User:
        """Create new object."""
        ...

    async def bulk_create(
        self,
        objects: list[User],
        *,
        batch_size: int | None = None,
        client: Any | None = None,
        using: str | None = None,
    ) -> list[User]:
        """Bulk create objects."""
        ...

    async def bulk_update(
        self,
        objects: list[User],
        fields: list[str],
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Bulk update objects."""
        ...



class TagQuery(Query[Tag]):
    """Type-safe Query for Tag model."""

    # Query building methods (sync, return Query)

    def filter(
        self,
        *args: Any,
        id: int | None = None,
        id__gt: int | None = None,
        id__gte: int | None = None,
        id__lt: int | None = None,
        id__lte: int | None = None,
        id__between: tuple[int, int] | None = None,
        id__range: int | None = None,
        id__in: list[int] | None = None,
        id__isnull: bool | None = None,
        name: str | None = None,
        name__contains: str | None = None,
        name__icontains: str | None = None,
        name__startswith: str | None = None,
        name__istartswith: str | None = None,
        name__endswith: str | None = None,
        name__iendswith: str | None = None,
        name__iexact: str | None = None,
        name__in: list[str] | None = None,
        name__isnull: bool | None = None,
        slug: str | None = None,
        slug__contains: str | None = None,
        slug__icontains: str | None = None,
        slug__startswith: str | None = None,
        slug__istartswith: str | None = None,
        slug__endswith: str | None = None,
        slug__iendswith: str | None = None,
        slug__iexact: str | None = None,
        slug__in: list[str] | None = None,
        slug__isnull: bool | None = None,
    ) -> "TagQuery":
        """Filter by Q-expressions or field lookups."""
        ...

    def exclude(
        self,
        *args: Any,
        id: int | None = None,
        id__gt: int | None = None,
        id__gte: int | None = None,
        id__lt: int | None = None,
        id__lte: int | None = None,
        id__between: tuple[int, int] | None = None,
        id__range: int | None = None,
        id__in: list[int] | None = None,
        id__isnull: bool | None = None,
        name: str | None = None,
        name__contains: str | None = None,
        name__icontains: str | None = None,
        name__startswith: str | None = None,
        name__istartswith: str | None = None,
        name__endswith: str | None = None,
        name__iendswith: str | None = None,
        name__iexact: str | None = None,
        name__in: list[str] | None = None,
        name__isnull: bool | None = None,
        slug: str | None = None,
        slug__contains: str | None = None,
        slug__icontains: str | None = None,
        slug__startswith: str | None = None,
        slug__istartswith: str | None = None,
        slug__endswith: str | None = None,
        slug__iendswith: str | None = None,
        slug__iexact: str | None = None,
        slug__in: list[str] | None = None,
        slug__isnull: bool | None = None,
    ) -> "TagQuery":
        """Exclude objects matching field lookups."""
        ...

    def order_by(self, *fields: Literal["id", "-id", "name", "-name", "slug", "-slug"]) -> "TagQuery":
        """Order results by fields."""
        ...

    def limit(self, n: int) -> "TagQuery":
        """Limit number of results."""
        ...

    def offset(self, n: int) -> "TagQuery":
        """Skip first n results."""
        ...

    def distinct(self, value: bool = True) -> "TagQuery":
        """Return distinct results."""
        ...

    def select(self, *fields: Literal["id", "name", "slug"]) -> "TagQuery":
        """Select specific fields."""
        ...

    def join(self, *paths: str) -> "TagQuery":
        """Perform LEFT JOIN for relations."""
        ...

    def prefetch(self, *paths: str) -> "TagQuery":
        """Prefetch related objects (separate queries)."""
        ...

    def for_update(self) -> "TagQuery":
        """Add FOR UPDATE lock to query."""
        ...

    def for_share(self) -> "TagQuery":
        """Add FOR SHARE lock to query."""
        ...

    def annotate(self, **annotations: Any) -> "TagQuery":
        """Add computed fields using aggregate functions."""
        ...

    def group_by(self, *fields: Literal["id", "name", "slug"]) -> "TagQuery":
        """Add GROUP BY clause."""
        ...

    def having(self, *q_exprs: Any, **kwargs: Any) -> "TagQuery":
        """Add HAVING clause for filtering grouped results."""
        ...

    def values(self, *fields: Literal["id", "name", "slug"]) -> "TagQuery":
        """Return dicts instead of models."""
        ...

    def values_list(self, *fields: Literal["id", "name", "slug"], flat: bool = False) -> "TagQuery":
        """Return tuples/values instead of models."""
        ...

    # Terminal methods (async, execute query)

    async def all(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> list[Tag]:
        """Execute query and return all results."""
        ...

    async def first(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Tag | None:
        """Execute query and return first result."""
        ...

    async def last(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Tag | None:
        """Execute query and return last result."""
        ...

    async def count(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Count matching objects."""
        ...

    async def sum(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate sum of field values."""
        ...

    async def avg(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate average of field values."""
        ...

    async def max(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get maximum field value."""
        ...

    async def min(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get minimum field value."""
        ...

    async def update(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **values: Any,
    ) -> int:
        """Update matching objects."""
        ...

    async def increment(
        self,
        field: str,
        by: int | float = 1,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Atomically increment a field value."""
        ...

    async def delete(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Delete matching objects."""
        ...

class TagManager(QueryManager[Tag]):
    """Type-safe Manager for Tag model."""

    # Query building methods (sync, return Query)

    def query(self) -> TagQuery:
        """Return a Query builder for this model."""
        ...

    def filter(
        self,
        *args: Any,
        id: int | None = None,
        id__gt: int | None = None,
        id__gte: int | None = None,
        id__lt: int | None = None,
        id__lte: int | None = None,
        id__between: tuple[int, int] | None = None,
        id__range: int | None = None,
        id__in: list[int] | None = None,
        id__isnull: bool | None = None,
        name: str | None = None,
        name__contains: str | None = None,
        name__icontains: str | None = None,
        name__startswith: str | None = None,
        name__istartswith: str | None = None,
        name__endswith: str | None = None,
        name__iendswith: str | None = None,
        name__iexact: str | None = None,
        name__in: list[str] | None = None,
        name__isnull: bool | None = None,
        slug: str | None = None,
        slug__contains: str | None = None,
        slug__icontains: str | None = None,
        slug__startswith: str | None = None,
        slug__istartswith: str | None = None,
        slug__endswith: str | None = None,
        slug__iendswith: str | None = None,
        slug__iexact: str | None = None,
        slug__in: list[str] | None = None,
        slug__isnull: bool | None = None,
    ) -> TagQuery:
        """Filter by Q-expressions or field lookups."""
        ...

    def exclude(
        self,
        *args: Any,
        id: int | None = None,
        id__gt: int | None = None,
        id__gte: int | None = None,
        id__lt: int | None = None,
        id__lte: int | None = None,
        id__between: tuple[int, int] | None = None,
        id__range: int | None = None,
        id__in: list[int] | None = None,
        id__isnull: bool | None = None,
        name: str | None = None,
        name__contains: str | None = None,
        name__icontains: str | None = None,
        name__startswith: str | None = None,
        name__istartswith: str | None = None,
        name__endswith: str | None = None,
        name__iendswith: str | None = None,
        name__iexact: str | None = None,
        name__in: list[str] | None = None,
        name__isnull: bool | None = None,
        slug: str | None = None,
        slug__contains: str | None = None,
        slug__icontains: str | None = None,
        slug__startswith: str | None = None,
        slug__istartswith: str | None = None,
        slug__endswith: str | None = None,
        slug__iendswith: str | None = None,
        slug__iexact: str | None = None,
        slug__in: list[str] | None = None,
        slug__isnull: bool | None = None,
    ) -> TagQuery:
        """Exclude objects matching field lookups."""
        ...

    def values(self, *fields: Literal["id", "name", "slug"]) -> TagQuery:
        """Return dicts instead of models."""
        ...

    def values_list(self, *fields: Literal["id", "name", "slug"], flat: bool = False) -> TagQuery:
        """Return tuples/values instead of models."""
        ...

    def distinct(self, distinct: bool = True) -> TagQuery:
        """Return distinct results."""
        ...

    def join(self, *paths: str) -> TagQuery:
        """Perform LEFT JOIN for relations."""
        ...

    def prefetch(self, *paths: str) -> TagQuery:
        """Prefetch related objects (separate queries)."""
        ...

    def for_update(self) -> TagQuery:
        """Add FOR UPDATE lock to query."""
        ...

    def for_share(self) -> TagQuery:
        """Add FOR SHARE lock to query."""
        ...

    # Terminal methods (async, execute query)

    async def get(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> Tag:
        """Get single object matching lookups."""
        ...

    async def get_or_none(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> Tag | None:
        """Get object or None if not found."""
        ...

    async def get_or_create(
        self,
        *,
        defaults: dict[str, Any] | None = None,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> tuple[Tag, bool]:
        """Get object or create if not found. Returns (object, created)."""
        ...

    async def all(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        mode: str = "models",
    ) -> list[Tag]:
        """Get all objects."""
        ...

    async def first(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Tag | None:
        """Get first object."""
        ...

    async def last(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Tag | None:
        """Get last object."""
        ...

    async def count(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Count all objects."""
        ...

    async def sum(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate sum of field values."""
        ...

    async def avg(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate average of field values."""
        ...

    async def max(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get maximum field value."""
        ...

    async def min(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get minimum field value."""
        ...

    async def create(
        self,
        *,
        instance: Tag | None = None,
        client: Any | None = None,
        using: str | None = None,
        id: int | None = None,
        name: str | None = None,
        slug: str | None = None,
    ) -> Tag:
        """Create new object."""
        ...

    async def bulk_create(
        self,
        objects: list[Tag],
        *,
        batch_size: int | None = None,
        client: Any | None = None,
        using: str | None = None,
    ) -> list[Tag]:
        """Bulk create objects."""
        ...

    async def bulk_update(
        self,
        objects: list[Tag],
        fields: list[str],
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Bulk update objects."""
        ...



class PostQuery(Query[Post]):
    """Type-safe Query for Post model."""

    # Query building methods (sync, return Query)

    def filter(
        self,
        *args: Any,
        author: User | None = None,
        author__in: list[User] | None = None,
        author__isnull: bool | None = None,
        author_id: int | None = None,
        author_id__gt: int | None = None,
        author_id__gte: int | None = None,
        author_id__lt: int | None = None,
        author_id__lte: int | None = None,
        author_id__between: tuple[int, int] | None = None,
        author_id__range: int | None = None,
        author_id__in: list[int] | None = None,
        author_id__isnull: bool | None = None,
        content: str | None = None,
        content__contains: str | None = None,
        content__icontains: str | None = None,
        content__startswith: str | None = None,
        content__istartswith: str | None = None,
        content__endswith: str | None = None,
        content__iendswith: str | None = None,
        content__iexact: str | None = None,
        content__in: list[str] | None = None,
        content__isnull: bool | None = None,
        created_at: datetime | None = None,
        created_at__gt: datetime | None = None,
        created_at__gte: datetime | None = None,
        created_at__lt: datetime | None = None,
        created_at__lte: datetime | None = None,
        created_at__between: tuple[datetime, datetime] | None = None,
        created_at__range: datetime | None = None,
        created_at__year: int | None = None,
        created_at__month: int | None = None,
        created_at__day: int | None = None,
        created_at__in: list[datetime] | None = None,
        created_at__isnull: bool | None = None,
        id: int | None = None,
        id__gt: int | None = None,
        id__gte: int | None = None,
        id__lt: int | None = None,
        id__lte: int | None = None,
        id__between: tuple[int, int] | None = None,
        id__range: int | None = None,
        id__in: list[int] | None = None,
        id__isnull: bool | None = None,
        published: bool | None = None,
        published__in: list[bool] | None = None,
        published__isnull: bool | None = None,
        title: str | None = None,
        title__contains: str | None = None,
        title__icontains: str | None = None,
        title__startswith: str | None = None,
        title__istartswith: str | None = None,
        title__endswith: str | None = None,
        title__iendswith: str | None = None,
        title__iexact: str | None = None,
        title__in: list[str] | None = None,
        title__isnull: bool | None = None,
        updated_at: datetime | None = None,
        updated_at__gt: datetime | None = None,
        updated_at__gte: datetime | None = None,
        updated_at__lt: datetime | None = None,
        updated_at__lte: datetime | None = None,
        updated_at__between: tuple[datetime, datetime] | None = None,
        updated_at__range: datetime | None = None,
        updated_at__year: int | None = None,
        updated_at__month: int | None = None,
        updated_at__day: int | None = None,
        updated_at__in: list[datetime] | None = None,
        updated_at__isnull: bool | None = None,
    ) -> "PostQuery":
        """Filter by Q-expressions or field lookups."""
        ...

    def exclude(
        self,
        *args: Any,
        author: User | None = None,
        author__in: list[User] | None = None,
        author__isnull: bool | None = None,
        author_id: int | None = None,
        author_id__gt: int | None = None,
        author_id__gte: int | None = None,
        author_id__lt: int | None = None,
        author_id__lte: int | None = None,
        author_id__between: tuple[int, int] | None = None,
        author_id__range: int | None = None,
        author_id__in: list[int] | None = None,
        author_id__isnull: bool | None = None,
        content: str | None = None,
        content__contains: str | None = None,
        content__icontains: str | None = None,
        content__startswith: str | None = None,
        content__istartswith: str | None = None,
        content__endswith: str | None = None,
        content__iendswith: str | None = None,
        content__iexact: str | None = None,
        content__in: list[str] | None = None,
        content__isnull: bool | None = None,
        created_at: datetime | None = None,
        created_at__gt: datetime | None = None,
        created_at__gte: datetime | None = None,
        created_at__lt: datetime | None = None,
        created_at__lte: datetime | None = None,
        created_at__between: tuple[datetime, datetime] | None = None,
        created_at__range: datetime | None = None,
        created_at__year: int | None = None,
        created_at__month: int | None = None,
        created_at__day: int | None = None,
        created_at__in: list[datetime] | None = None,
        created_at__isnull: bool | None = None,
        id: int | None = None,
        id__gt: int | None = None,
        id__gte: int | None = None,
        id__lt: int | None = None,
        id__lte: int | None = None,
        id__between: tuple[int, int] | None = None,
        id__range: int | None = None,
        id__in: list[int] | None = None,
        id__isnull: bool | None = None,
        published: bool | None = None,
        published__in: list[bool] | None = None,
        published__isnull: bool | None = None,
        title: str | None = None,
        title__contains: str | None = None,
        title__icontains: str | None = None,
        title__startswith: str | None = None,
        title__istartswith: str | None = None,
        title__endswith: str | None = None,
        title__iendswith: str | None = None,
        title__iexact: str | None = None,
        title__in: list[str] | None = None,
        title__isnull: bool | None = None,
        updated_at: datetime | None = None,
        updated_at__gt: datetime | None = None,
        updated_at__gte: datetime | None = None,
        updated_at__lt: datetime | None = None,
        updated_at__lte: datetime | None = None,
        updated_at__between: tuple[datetime, datetime] | None = None,
        updated_at__range: datetime | None = None,
        updated_at__year: int | None = None,
        updated_at__month: int | None = None,
        updated_at__day: int | None = None,
        updated_at__in: list[datetime] | None = None,
        updated_at__isnull: bool | None = None,
    ) -> "PostQuery":
        """Exclude objects matching field lookups."""
        ...

    def order_by(self, *fields: Literal["author", "-author", "author_id", "-author_id", "content", "-content", "created_at", "-created_at", "id", "-id", "published", "-published", "title", "-title", "updated_at", "-updated_at"]) -> "PostQuery":
        """Order results by fields."""
        ...

    def limit(self, n: int) -> "PostQuery":
        """Limit number of results."""
        ...

    def offset(self, n: int) -> "PostQuery":
        """Skip first n results."""
        ...

    def distinct(self, value: bool = True) -> "PostQuery":
        """Return distinct results."""
        ...

    def select(self, *fields: Literal["author", "author_id", "content", "created_at", "id", "published", "title", "updated_at"]) -> "PostQuery":
        """Select specific fields."""
        ...

    def join(self, *paths: str) -> "PostQuery":
        """Perform LEFT JOIN for relations."""
        ...

    def prefetch(self, *paths: str) -> "PostQuery":
        """Prefetch related objects (separate queries)."""
        ...

    def for_update(self) -> "PostQuery":
        """Add FOR UPDATE lock to query."""
        ...

    def for_share(self) -> "PostQuery":
        """Add FOR SHARE lock to query."""
        ...

    def annotate(self, **annotations: Any) -> "PostQuery":
        """Add computed fields using aggregate functions."""
        ...

    def group_by(self, *fields: Literal["author", "author_id", "content", "created_at", "id", "published", "title", "updated_at"]) -> "PostQuery":
        """Add GROUP BY clause."""
        ...

    def having(self, *q_exprs: Any, **kwargs: Any) -> "PostQuery":
        """Add HAVING clause for filtering grouped results."""
        ...

    def values(self, *fields: Literal["author", "author_id", "content", "created_at", "id", "published", "title", "updated_at"]) -> "PostQuery":
        """Return dicts instead of models."""
        ...

    def values_list(self, *fields: Literal["author", "author_id", "content", "created_at", "id", "published", "title", "updated_at"], flat: bool = False) -> "PostQuery":
        """Return tuples/values instead of models."""
        ...

    # Terminal methods (async, execute query)

    async def all(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> list[Post]:
        """Execute query and return all results."""
        ...

    async def first(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Post | None:
        """Execute query and return first result."""
        ...

    async def last(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Post | None:
        """Execute query and return last result."""
        ...

    async def count(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Count matching objects."""
        ...

    async def sum(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate sum of field values."""
        ...

    async def avg(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate average of field values."""
        ...

    async def max(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get maximum field value."""
        ...

    async def min(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get minimum field value."""
        ...

    async def update(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **values: Any,
    ) -> int:
        """Update matching objects."""
        ...

    async def increment(
        self,
        field: str,
        by: int | float = 1,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Atomically increment a field value."""
        ...

    async def delete(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Delete matching objects."""
        ...

class PostManager(QueryManager[Post]):
    """Type-safe Manager for Post model."""

    # Query building methods (sync, return Query)

    def query(self) -> PostQuery:
        """Return a Query builder for this model."""
        ...

    def filter(
        self,
        *args: Any,
        author: User | None = None,
        author__in: list[User] | None = None,
        author__isnull: bool | None = None,
        author_id: int | None = None,
        author_id__gt: int | None = None,
        author_id__gte: int | None = None,
        author_id__lt: int | None = None,
        author_id__lte: int | None = None,
        author_id__between: tuple[int, int] | None = None,
        author_id__range: int | None = None,
        author_id__in: list[int] | None = None,
        author_id__isnull: bool | None = None,
        content: str | None = None,
        content__contains: str | None = None,
        content__icontains: str | None = None,
        content__startswith: str | None = None,
        content__istartswith: str | None = None,
        content__endswith: str | None = None,
        content__iendswith: str | None = None,
        content__iexact: str | None = None,
        content__in: list[str] | None = None,
        content__isnull: bool | None = None,
        created_at: datetime | None = None,
        created_at__gt: datetime | None = None,
        created_at__gte: datetime | None = None,
        created_at__lt: datetime | None = None,
        created_at__lte: datetime | None = None,
        created_at__between: tuple[datetime, datetime] | None = None,
        created_at__range: datetime | None = None,
        created_at__year: int | None = None,
        created_at__month: int | None = None,
        created_at__day: int | None = None,
        created_at__in: list[datetime] | None = None,
        created_at__isnull: bool | None = None,
        id: int | None = None,
        id__gt: int | None = None,
        id__gte: int | None = None,
        id__lt: int | None = None,
        id__lte: int | None = None,
        id__between: tuple[int, int] | None = None,
        id__range: int | None = None,
        id__in: list[int] | None = None,
        id__isnull: bool | None = None,
        published: bool | None = None,
        published__in: list[bool] | None = None,
        published__isnull: bool | None = None,
        title: str | None = None,
        title__contains: str | None = None,
        title__icontains: str | None = None,
        title__startswith: str | None = None,
        title__istartswith: str | None = None,
        title__endswith: str | None = None,
        title__iendswith: str | None = None,
        title__iexact: str | None = None,
        title__in: list[str] | None = None,
        title__isnull: bool | None = None,
        updated_at: datetime | None = None,
        updated_at__gt: datetime | None = None,
        updated_at__gte: datetime | None = None,
        updated_at__lt: datetime | None = None,
        updated_at__lte: datetime | None = None,
        updated_at__between: tuple[datetime, datetime] | None = None,
        updated_at__range: datetime | None = None,
        updated_at__year: int | None = None,
        updated_at__month: int | None = None,
        updated_at__day: int | None = None,
        updated_at__in: list[datetime] | None = None,
        updated_at__isnull: bool | None = None,
    ) -> PostQuery:
        """Filter by Q-expressions or field lookups."""
        ...

    def exclude(
        self,
        *args: Any,
        author: User | None = None,
        author__in: list[User] | None = None,
        author__isnull: bool | None = None,
        author_id: int | None = None,
        author_id__gt: int | None = None,
        author_id__gte: int | None = None,
        author_id__lt: int | None = None,
        author_id__lte: int | None = None,
        author_id__between: tuple[int, int] | None = None,
        author_id__range: int | None = None,
        author_id__in: list[int] | None = None,
        author_id__isnull: bool | None = None,
        content: str | None = None,
        content__contains: str | None = None,
        content__icontains: str | None = None,
        content__startswith: str | None = None,
        content__istartswith: str | None = None,
        content__endswith: str | None = None,
        content__iendswith: str | None = None,
        content__iexact: str | None = None,
        content__in: list[str] | None = None,
        content__isnull: bool | None = None,
        created_at: datetime | None = None,
        created_at__gt: datetime | None = None,
        created_at__gte: datetime | None = None,
        created_at__lt: datetime | None = None,
        created_at__lte: datetime | None = None,
        created_at__between: tuple[datetime, datetime] | None = None,
        created_at__range: datetime | None = None,
        created_at__year: int | None = None,
        created_at__month: int | None = None,
        created_at__day: int | None = None,
        created_at__in: list[datetime] | None = None,
        created_at__isnull: bool | None = None,
        id: int | None = None,
        id__gt: int | None = None,
        id__gte: int | None = None,
        id__lt: int | None = None,
        id__lte: int | None = None,
        id__between: tuple[int, int] | None = None,
        id__range: int | None = None,
        id__in: list[int] | None = None,
        id__isnull: bool | None = None,
        published: bool | None = None,
        published__in: list[bool] | None = None,
        published__isnull: bool | None = None,
        title: str | None = None,
        title__contains: str | None = None,
        title__icontains: str | None = None,
        title__startswith: str | None = None,
        title__istartswith: str | None = None,
        title__endswith: str | None = None,
        title__iendswith: str | None = None,
        title__iexact: str | None = None,
        title__in: list[str] | None = None,
        title__isnull: bool | None = None,
        updated_at: datetime | None = None,
        updated_at__gt: datetime | None = None,
        updated_at__gte: datetime | None = None,
        updated_at__lt: datetime | None = None,
        updated_at__lte: datetime | None = None,
        updated_at__between: tuple[datetime, datetime] | None = None,
        updated_at__range: datetime | None = None,
        updated_at__year: int | None = None,
        updated_at__month: int | None = None,
        updated_at__day: int | None = None,
        updated_at__in: list[datetime] | None = None,
        updated_at__isnull: bool | None = None,
    ) -> PostQuery:
        """Exclude objects matching field lookups."""
        ...

    def values(self, *fields: Literal["author", "author_id", "content", "created_at", "id", "published", "title", "updated_at"]) -> PostQuery:
        """Return dicts instead of models."""
        ...

    def values_list(self, *fields: Literal["author", "author_id", "content", "created_at", "id", "published", "title", "updated_at"], flat: bool = False) -> PostQuery:
        """Return tuples/values instead of models."""
        ...

    def distinct(self, distinct: bool = True) -> PostQuery:
        """Return distinct results."""
        ...

    def join(self, *paths: str) -> PostQuery:
        """Perform LEFT JOIN for relations."""
        ...

    def prefetch(self, *paths: str) -> PostQuery:
        """Prefetch related objects (separate queries)."""
        ...

    def for_update(self) -> PostQuery:
        """Add FOR UPDATE lock to query."""
        ...

    def for_share(self) -> PostQuery:
        """Add FOR SHARE lock to query."""
        ...

    # Terminal methods (async, execute query)

    async def get(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> Post:
        """Get single object matching lookups."""
        ...

    async def get_or_none(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> Post | None:
        """Get object or None if not found."""
        ...

    async def get_or_create(
        self,
        *,
        defaults: dict[str, Any] | None = None,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> tuple[Post, bool]:
        """Get object or create if not found. Returns (object, created)."""
        ...

    async def all(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        mode: str = "models",
    ) -> list[Post]:
        """Get all objects."""
        ...

    async def first(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Post | None:
        """Get first object."""
        ...

    async def last(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Post | None:
        """Get last object."""
        ...

    async def count(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Count all objects."""
        ...

    async def sum(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate sum of field values."""
        ...

    async def avg(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate average of field values."""
        ...

    async def max(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get maximum field value."""
        ...

    async def min(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get minimum field value."""
        ...

    async def create(
        self,
        *,
        instance: Post | None = None,
        client: Any | None = None,
        using: str | None = None,
        author: User | None = None,
        author_id: int | None = None,
        content: str | None = None,
        created_at: datetime | None = None,
        id: int | None = None,
        published: bool | None = None,
        title: str | None = None,
        updated_at: datetime | None = None,
    ) -> Post:
        """Create new object."""
        ...

    async def bulk_create(
        self,
        objects: list[Post],
        *,
        batch_size: int | None = None,
        client: Any | None = None,
        using: str | None = None,
    ) -> list[Post]:
        """Bulk create objects."""
        ...

    async def bulk_update(
        self,
        objects: list[Post],
        fields: list[str],
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Bulk update objects."""
        ...



class CommentQuery(Query[Comment]):
    """Type-safe Query for Comment model."""

    # Query building methods (sync, return Query)

    def filter(
        self,
        *args: Any,
        author: User | None = None,
        author__in: list[User] | None = None,
        author__isnull: bool | None = None,
        author_id: int | None = None,
        author_id__gt: int | None = None,
        author_id__gte: int | None = None,
        author_id__lt: int | None = None,
        author_id__lte: int | None = None,
        author_id__between: tuple[int, int] | None = None,
        author_id__range: int | None = None,
        author_id__in: list[int] | None = None,
        author_id__isnull: bool | None = None,
        content: str | None = None,
        content__contains: str | None = None,
        content__icontains: str | None = None,
        content__startswith: str | None = None,
        content__istartswith: str | None = None,
        content__endswith: str | None = None,
        content__iendswith: str | None = None,
        content__iexact: str | None = None,
        content__in: list[str] | None = None,
        content__isnull: bool | None = None,
        created_at: datetime | None = None,
        created_at__gt: datetime | None = None,
        created_at__gte: datetime | None = None,
        created_at__lt: datetime | None = None,
        created_at__lte: datetime | None = None,
        created_at__between: tuple[datetime, datetime] | None = None,
        created_at__range: datetime | None = None,
        created_at__year: int | None = None,
        created_at__month: int | None = None,
        created_at__day: int | None = None,
        created_at__in: list[datetime] | None = None,
        created_at__isnull: bool | None = None,
        id: int | None = None,
        id__gt: int | None = None,
        id__gte: int | None = None,
        id__lt: int | None = None,
        id__lte: int | None = None,
        id__between: tuple[int, int] | None = None,
        id__range: int | None = None,
        id__in: list[int] | None = None,
        id__isnull: bool | None = None,
        post: Post | None = None,
        post__in: list[Post] | None = None,
        post__isnull: bool | None = None,
        post_id: int | None = None,
        post_id__gt: int | None = None,
        post_id__gte: int | None = None,
        post_id__lt: int | None = None,
        post_id__lte: int | None = None,
        post_id__between: tuple[int, int] | None = None,
        post_id__range: int | None = None,
        post_id__in: list[int] | None = None,
        post_id__isnull: bool | None = None,
    ) -> "CommentQuery":
        """Filter by Q-expressions or field lookups."""
        ...

    def exclude(
        self,
        *args: Any,
        author: User | None = None,
        author__in: list[User] | None = None,
        author__isnull: bool | None = None,
        author_id: int | None = None,
        author_id__gt: int | None = None,
        author_id__gte: int | None = None,
        author_id__lt: int | None = None,
        author_id__lte: int | None = None,
        author_id__between: tuple[int, int] | None = None,
        author_id__range: int | None = None,
        author_id__in: list[int] | None = None,
        author_id__isnull: bool | None = None,
        content: str | None = None,
        content__contains: str | None = None,
        content__icontains: str | None = None,
        content__startswith: str | None = None,
        content__istartswith: str | None = None,
        content__endswith: str | None = None,
        content__iendswith: str | None = None,
        content__iexact: str | None = None,
        content__in: list[str] | None = None,
        content__isnull: bool | None = None,
        created_at: datetime | None = None,
        created_at__gt: datetime | None = None,
        created_at__gte: datetime | None = None,
        created_at__lt: datetime | None = None,
        created_at__lte: datetime | None = None,
        created_at__between: tuple[datetime, datetime] | None = None,
        created_at__range: datetime | None = None,
        created_at__year: int | None = None,
        created_at__month: int | None = None,
        created_at__day: int | None = None,
        created_at__in: list[datetime] | None = None,
        created_at__isnull: bool | None = None,
        id: int | None = None,
        id__gt: int | None = None,
        id__gte: int | None = None,
        id__lt: int | None = None,
        id__lte: int | None = None,
        id__between: tuple[int, int] | None = None,
        id__range: int | None = None,
        id__in: list[int] | None = None,
        id__isnull: bool | None = None,
        post: Post | None = None,
        post__in: list[Post] | None = None,
        post__isnull: bool | None = None,
        post_id: int | None = None,
        post_id__gt: int | None = None,
        post_id__gte: int | None = None,
        post_id__lt: int | None = None,
        post_id__lte: int | None = None,
        post_id__between: tuple[int, int] | None = None,
        post_id__range: int | None = None,
        post_id__in: list[int] | None = None,
        post_id__isnull: bool | None = None,
    ) -> "CommentQuery":
        """Exclude objects matching field lookups."""
        ...

    def order_by(self, *fields: Literal["author", "-author", "author_id", "-author_id", "content", "-content", "created_at", "-created_at", "id", "-id", "post", "-post", "post_id", "-post_id"]) -> "CommentQuery":
        """Order results by fields."""
        ...

    def limit(self, n: int) -> "CommentQuery":
        """Limit number of results."""
        ...

    def offset(self, n: int) -> "CommentQuery":
        """Skip first n results."""
        ...

    def distinct(self, value: bool = True) -> "CommentQuery":
        """Return distinct results."""
        ...

    def select(self, *fields: Literal["author", "author_id", "content", "created_at", "id", "post", "post_id"]) -> "CommentQuery":
        """Select specific fields."""
        ...

    def join(self, *paths: str) -> "CommentQuery":
        """Perform LEFT JOIN for relations."""
        ...

    def prefetch(self, *paths: str) -> "CommentQuery":
        """Prefetch related objects (separate queries)."""
        ...

    def for_update(self) -> "CommentQuery":
        """Add FOR UPDATE lock to query."""
        ...

    def for_share(self) -> "CommentQuery":
        """Add FOR SHARE lock to query."""
        ...

    def annotate(self, **annotations: Any) -> "CommentQuery":
        """Add computed fields using aggregate functions."""
        ...

    def group_by(self, *fields: Literal["author", "author_id", "content", "created_at", "id", "post", "post_id"]) -> "CommentQuery":
        """Add GROUP BY clause."""
        ...

    def having(self, *q_exprs: Any, **kwargs: Any) -> "CommentQuery":
        """Add HAVING clause for filtering grouped results."""
        ...

    def values(self, *fields: Literal["author", "author_id", "content", "created_at", "id", "post", "post_id"]) -> "CommentQuery":
        """Return dicts instead of models."""
        ...

    def values_list(self, *fields: Literal["author", "author_id", "content", "created_at", "id", "post", "post_id"], flat: bool = False) -> "CommentQuery":
        """Return tuples/values instead of models."""
        ...

    # Terminal methods (async, execute query)

    async def all(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> list[Comment]:
        """Execute query and return all results."""
        ...

    async def first(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Comment | None:
        """Execute query and return first result."""
        ...

    async def last(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Comment | None:
        """Execute query and return last result."""
        ...

    async def count(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Count matching objects."""
        ...

    async def sum(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate sum of field values."""
        ...

    async def avg(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate average of field values."""
        ...

    async def max(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get maximum field value."""
        ...

    async def min(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get minimum field value."""
        ...

    async def update(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **values: Any,
    ) -> int:
        """Update matching objects."""
        ...

    async def increment(
        self,
        field: str,
        by: int | float = 1,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Atomically increment a field value."""
        ...

    async def delete(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Delete matching objects."""
        ...

class CommentManager(QueryManager[Comment]):
    """Type-safe Manager for Comment model."""

    # Query building methods (sync, return Query)

    def query(self) -> CommentQuery:
        """Return a Query builder for this model."""
        ...

    def filter(
        self,
        *args: Any,
        author: User | None = None,
        author__in: list[User] | None = None,
        author__isnull: bool | None = None,
        author_id: int | None = None,
        author_id__gt: int | None = None,
        author_id__gte: int | None = None,
        author_id__lt: int | None = None,
        author_id__lte: int | None = None,
        author_id__between: tuple[int, int] | None = None,
        author_id__range: int | None = None,
        author_id__in: list[int] | None = None,
        author_id__isnull: bool | None = None,
        content: str | None = None,
        content__contains: str | None = None,
        content__icontains: str | None = None,
        content__startswith: str | None = None,
        content__istartswith: str | None = None,
        content__endswith: str | None = None,
        content__iendswith: str | None = None,
        content__iexact: str | None = None,
        content__in: list[str] | None = None,
        content__isnull: bool | None = None,
        created_at: datetime | None = None,
        created_at__gt: datetime | None = None,
        created_at__gte: datetime | None = None,
        created_at__lt: datetime | None = None,
        created_at__lte: datetime | None = None,
        created_at__between: tuple[datetime, datetime] | None = None,
        created_at__range: datetime | None = None,
        created_at__year: int | None = None,
        created_at__month: int | None = None,
        created_at__day: int | None = None,
        created_at__in: list[datetime] | None = None,
        created_at__isnull: bool | None = None,
        id: int | None = None,
        id__gt: int | None = None,
        id__gte: int | None = None,
        id__lt: int | None = None,
        id__lte: int | None = None,
        id__between: tuple[int, int] | None = None,
        id__range: int | None = None,
        id__in: list[int] | None = None,
        id__isnull: bool | None = None,
        post: Post | None = None,
        post__in: list[Post] | None = None,
        post__isnull: bool | None = None,
        post_id: int | None = None,
        post_id__gt: int | None = None,
        post_id__gte: int | None = None,
        post_id__lt: int | None = None,
        post_id__lte: int | None = None,
        post_id__between: tuple[int, int] | None = None,
        post_id__range: int | None = None,
        post_id__in: list[int] | None = None,
        post_id__isnull: bool | None = None,
    ) -> CommentQuery:
        """Filter by Q-expressions or field lookups."""
        ...

    def exclude(
        self,
        *args: Any,
        author: User | None = None,
        author__in: list[User] | None = None,
        author__isnull: bool | None = None,
        author_id: int | None = None,
        author_id__gt: int | None = None,
        author_id__gte: int | None = None,
        author_id__lt: int | None = None,
        author_id__lte: int | None = None,
        author_id__between: tuple[int, int] | None = None,
        author_id__range: int | None = None,
        author_id__in: list[int] | None = None,
        author_id__isnull: bool | None = None,
        content: str | None = None,
        content__contains: str | None = None,
        content__icontains: str | None = None,
        content__startswith: str | None = None,
        content__istartswith: str | None = None,
        content__endswith: str | None = None,
        content__iendswith: str | None = None,
        content__iexact: str | None = None,
        content__in: list[str] | None = None,
        content__isnull: bool | None = None,
        created_at: datetime | None = None,
        created_at__gt: datetime | None = None,
        created_at__gte: datetime | None = None,
        created_at__lt: datetime | None = None,
        created_at__lte: datetime | None = None,
        created_at__between: tuple[datetime, datetime] | None = None,
        created_at__range: datetime | None = None,
        created_at__year: int | None = None,
        created_at__month: int | None = None,
        created_at__day: int | None = None,
        created_at__in: list[datetime] | None = None,
        created_at__isnull: bool | None = None,
        id: int | None = None,
        id__gt: int | None = None,
        id__gte: int | None = None,
        id__lt: int | None = None,
        id__lte: int | None = None,
        id__between: tuple[int, int] | None = None,
        id__range: int | None = None,
        id__in: list[int] | None = None,
        id__isnull: bool | None = None,
        post: Post | None = None,
        post__in: list[Post] | None = None,
        post__isnull: bool | None = None,
        post_id: int | None = None,
        post_id__gt: int | None = None,
        post_id__gte: int | None = None,
        post_id__lt: int | None = None,
        post_id__lte: int | None = None,
        post_id__between: tuple[int, int] | None = None,
        post_id__range: int | None = None,
        post_id__in: list[int] | None = None,
        post_id__isnull: bool | None = None,
    ) -> CommentQuery:
        """Exclude objects matching field lookups."""
        ...

    def values(self, *fields: Literal["author", "author_id", "content", "created_at", "id", "post", "post_id"]) -> CommentQuery:
        """Return dicts instead of models."""
        ...

    def values_list(self, *fields: Literal["author", "author_id", "content", "created_at", "id", "post", "post_id"], flat: bool = False) -> CommentQuery:
        """Return tuples/values instead of models."""
        ...

    def distinct(self, distinct: bool = True) -> CommentQuery:
        """Return distinct results."""
        ...

    def join(self, *paths: str) -> CommentQuery:
        """Perform LEFT JOIN for relations."""
        ...

    def prefetch(self, *paths: str) -> CommentQuery:
        """Prefetch related objects (separate queries)."""
        ...

    def for_update(self) -> CommentQuery:
        """Add FOR UPDATE lock to query."""
        ...

    def for_share(self) -> CommentQuery:
        """Add FOR SHARE lock to query."""
        ...

    # Terminal methods (async, execute query)

    async def get(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> Comment:
        """Get single object matching lookups."""
        ...

    async def get_or_none(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> Comment | None:
        """Get object or None if not found."""
        ...

    async def get_or_create(
        self,
        *,
        defaults: dict[str, Any] | None = None,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> tuple[Comment, bool]:
        """Get object or create if not found. Returns (object, created)."""
        ...

    async def all(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        mode: str = "models",
    ) -> list[Comment]:
        """Get all objects."""
        ...

    async def first(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Comment | None:
        """Get first object."""
        ...

    async def last(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Comment | None:
        """Get last object."""
        ...

    async def count(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Count all objects."""
        ...

    async def sum(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate sum of field values."""
        ...

    async def avg(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate average of field values."""
        ...

    async def max(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get maximum field value."""
        ...

    async def min(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get minimum field value."""
        ...

    async def create(
        self,
        *,
        instance: Comment | None = None,
        client: Any | None = None,
        using: str | None = None,
        author: User | None = None,
        author_id: int | None = None,
        content: str | None = None,
        created_at: datetime | None = None,
        id: int | None = None,
        post: Post | None = None,
        post_id: int | None = None,
    ) -> Comment:
        """Create new object."""
        ...

    async def bulk_create(
        self,
        objects: list[Comment],
        *,
        batch_size: int | None = None,
        client: Any | None = None,
        using: str | None = None,
    ) -> list[Comment]:
        """Bulk create objects."""
        ...

    async def bulk_update(
        self,
        objects: list[Comment],
        fields: list[str],
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Bulk update objects."""
        ...



class PostTagQuery(Query[PostTag]):
    """Type-safe Query for PostTag model."""

    # Query building methods (sync, return Query)

    def filter(
        self,
        *args: Any,
        id: int | None = None,
        id__gt: int | None = None,
        id__gte: int | None = None,
        id__lt: int | None = None,
        id__lte: int | None = None,
        id__between: tuple[int, int] | None = None,
        id__range: int | None = None,
        id__in: list[int] | None = None,
        id__isnull: bool | None = None,
        post: Post | None = None,
        post__in: list[Post] | None = None,
        post__isnull: bool | None = None,
        post_id: int | None = None,
        post_id__gt: int | None = None,
        post_id__gte: int | None = None,
        post_id__lt: int | None = None,
        post_id__lte: int | None = None,
        post_id__between: tuple[int, int] | None = None,
        post_id__range: int | None = None,
        post_id__in: list[int] | None = None,
        post_id__isnull: bool | None = None,
        tag: Tag | None = None,
        tag__in: list[Tag] | None = None,
        tag__isnull: bool | None = None,
        tag_id: int | None = None,
        tag_id__gt: int | None = None,
        tag_id__gte: int | None = None,
        tag_id__lt: int | None = None,
        tag_id__lte: int | None = None,
        tag_id__between: tuple[int, int] | None = None,
        tag_id__range: int | None = None,
        tag_id__in: list[int] | None = None,
        tag_id__isnull: bool | None = None,
    ) -> "PostTagQuery":
        """Filter by Q-expressions or field lookups."""
        ...

    def exclude(
        self,
        *args: Any,
        id: int | None = None,
        id__gt: int | None = None,
        id__gte: int | None = None,
        id__lt: int | None = None,
        id__lte: int | None = None,
        id__between: tuple[int, int] | None = None,
        id__range: int | None = None,
        id__in: list[int] | None = None,
        id__isnull: bool | None = None,
        post: Post | None = None,
        post__in: list[Post] | None = None,
        post__isnull: bool | None = None,
        post_id: int | None = None,
        post_id__gt: int | None = None,
        post_id__gte: int | None = None,
        post_id__lt: int | None = None,
        post_id__lte: int | None = None,
        post_id__between: tuple[int, int] | None = None,
        post_id__range: int | None = None,
        post_id__in: list[int] | None = None,
        post_id__isnull: bool | None = None,
        tag: Tag | None = None,
        tag__in: list[Tag] | None = None,
        tag__isnull: bool | None = None,
        tag_id: int | None = None,
        tag_id__gt: int | None = None,
        tag_id__gte: int | None = None,
        tag_id__lt: int | None = None,
        tag_id__lte: int | None = None,
        tag_id__between: tuple[int, int] | None = None,
        tag_id__range: int | None = None,
        tag_id__in: list[int] | None = None,
        tag_id__isnull: bool | None = None,
    ) -> "PostTagQuery":
        """Exclude objects matching field lookups."""
        ...

    def order_by(self, *fields: Literal["id", "-id", "post", "-post", "post_id", "-post_id", "tag", "-tag", "tag_id", "-tag_id"]) -> "PostTagQuery":
        """Order results by fields."""
        ...

    def limit(self, n: int) -> "PostTagQuery":
        """Limit number of results."""
        ...

    def offset(self, n: int) -> "PostTagQuery":
        """Skip first n results."""
        ...

    def distinct(self, value: bool = True) -> "PostTagQuery":
        """Return distinct results."""
        ...

    def select(self, *fields: Literal["id", "post", "post_id", "tag", "tag_id"]) -> "PostTagQuery":
        """Select specific fields."""
        ...

    def join(self, *paths: str) -> "PostTagQuery":
        """Perform LEFT JOIN for relations."""
        ...

    def prefetch(self, *paths: str) -> "PostTagQuery":
        """Prefetch related objects (separate queries)."""
        ...

    def for_update(self) -> "PostTagQuery":
        """Add FOR UPDATE lock to query."""
        ...

    def for_share(self) -> "PostTagQuery":
        """Add FOR SHARE lock to query."""
        ...

    def annotate(self, **annotations: Any) -> "PostTagQuery":
        """Add computed fields using aggregate functions."""
        ...

    def group_by(self, *fields: Literal["id", "post", "post_id", "tag", "tag_id"]) -> "PostTagQuery":
        """Add GROUP BY clause."""
        ...

    def having(self, *q_exprs: Any, **kwargs: Any) -> "PostTagQuery":
        """Add HAVING clause for filtering grouped results."""
        ...

    def values(self, *fields: Literal["id", "post", "post_id", "tag", "tag_id"]) -> "PostTagQuery":
        """Return dicts instead of models."""
        ...

    def values_list(self, *fields: Literal["id", "post", "post_id", "tag", "tag_id"], flat: bool = False) -> "PostTagQuery":
        """Return tuples/values instead of models."""
        ...

    # Terminal methods (async, execute query)

    async def all(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> list[PostTag]:
        """Execute query and return all results."""
        ...

    async def first(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> PostTag | None:
        """Execute query and return first result."""
        ...

    async def last(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> PostTag | None:
        """Execute query and return last result."""
        ...

    async def count(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Count matching objects."""
        ...

    async def sum(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate sum of field values."""
        ...

    async def avg(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate average of field values."""
        ...

    async def max(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get maximum field value."""
        ...

    async def min(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get minimum field value."""
        ...

    async def update(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **values: Any,
    ) -> int:
        """Update matching objects."""
        ...

    async def increment(
        self,
        field: str,
        by: int | float = 1,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Atomically increment a field value."""
        ...

    async def delete(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Delete matching objects."""
        ...

class PostTagManager(QueryManager[PostTag]):
    """Type-safe Manager for PostTag model."""

    # Query building methods (sync, return Query)

    def query(self) -> PostTagQuery:
        """Return a Query builder for this model."""
        ...

    def filter(
        self,
        *args: Any,
        id: int | None = None,
        id__gt: int | None = None,
        id__gte: int | None = None,
        id__lt: int | None = None,
        id__lte: int | None = None,
        id__between: tuple[int, int] | None = None,
        id__range: int | None = None,
        id__in: list[int] | None = None,
        id__isnull: bool | None = None,
        post: Post | None = None,
        post__in: list[Post] | None = None,
        post__isnull: bool | None = None,
        post_id: int | None = None,
        post_id__gt: int | None = None,
        post_id__gte: int | None = None,
        post_id__lt: int | None = None,
        post_id__lte: int | None = None,
        post_id__between: tuple[int, int] | None = None,
        post_id__range: int | None = None,
        post_id__in: list[int] | None = None,
        post_id__isnull: bool | None = None,
        tag: Tag | None = None,
        tag__in: list[Tag] | None = None,
        tag__isnull: bool | None = None,
        tag_id: int | None = None,
        tag_id__gt: int | None = None,
        tag_id__gte: int | None = None,
        tag_id__lt: int | None = None,
        tag_id__lte: int | None = None,
        tag_id__between: tuple[int, int] | None = None,
        tag_id__range: int | None = None,
        tag_id__in: list[int] | None = None,
        tag_id__isnull: bool | None = None,
    ) -> PostTagQuery:
        """Filter by Q-expressions or field lookups."""
        ...

    def exclude(
        self,
        *args: Any,
        id: int | None = None,
        id__gt: int | None = None,
        id__gte: int | None = None,
        id__lt: int | None = None,
        id__lte: int | None = None,
        id__between: tuple[int, int] | None = None,
        id__range: int | None = None,
        id__in: list[int] | None = None,
        id__isnull: bool | None = None,
        post: Post | None = None,
        post__in: list[Post] | None = None,
        post__isnull: bool | None = None,
        post_id: int | None = None,
        post_id__gt: int | None = None,
        post_id__gte: int | None = None,
        post_id__lt: int | None = None,
        post_id__lte: int | None = None,
        post_id__between: tuple[int, int] | None = None,
        post_id__range: int | None = None,
        post_id__in: list[int] | None = None,
        post_id__isnull: bool | None = None,
        tag: Tag | None = None,
        tag__in: list[Tag] | None = None,
        tag__isnull: bool | None = None,
        tag_id: int | None = None,
        tag_id__gt: int | None = None,
        tag_id__gte: int | None = None,
        tag_id__lt: int | None = None,
        tag_id__lte: int | None = None,
        tag_id__between: tuple[int, int] | None = None,
        tag_id__range: int | None = None,
        tag_id__in: list[int] | None = None,
        tag_id__isnull: bool | None = None,
    ) -> PostTagQuery:
        """Exclude objects matching field lookups."""
        ...

    def values(self, *fields: Literal["id", "post", "post_id", "tag", "tag_id"]) -> PostTagQuery:
        """Return dicts instead of models."""
        ...

    def values_list(self, *fields: Literal["id", "post", "post_id", "tag", "tag_id"], flat: bool = False) -> PostTagQuery:
        """Return tuples/values instead of models."""
        ...

    def distinct(self, distinct: bool = True) -> PostTagQuery:
        """Return distinct results."""
        ...

    def join(self, *paths: str) -> PostTagQuery:
        """Perform LEFT JOIN for relations."""
        ...

    def prefetch(self, *paths: str) -> PostTagQuery:
        """Prefetch related objects (separate queries)."""
        ...

    def for_update(self) -> PostTagQuery:
        """Add FOR UPDATE lock to query."""
        ...

    def for_share(self) -> PostTagQuery:
        """Add FOR SHARE lock to query."""
        ...

    # Terminal methods (async, execute query)

    async def get(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> PostTag:
        """Get single object matching lookups."""
        ...

    async def get_or_none(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> PostTag | None:
        """Get object or None if not found."""
        ...

    async def get_or_create(
        self,
        *,
        defaults: dict[str, Any] | None = None,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> tuple[PostTag, bool]:
        """Get object or create if not found. Returns (object, created)."""
        ...

    async def all(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        mode: str = "models",
    ) -> list[PostTag]:
        """Get all objects."""
        ...

    async def first(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> PostTag | None:
        """Get first object."""
        ...

    async def last(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> PostTag | None:
        """Get last object."""
        ...

    async def count(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Count all objects."""
        ...

    async def sum(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate sum of field values."""
        ...

    async def avg(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate average of field values."""
        ...

    async def max(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get maximum field value."""
        ...

    async def min(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get minimum field value."""
        ...

    async def create(
        self,
        *,
        instance: PostTag | None = None,
        client: Any | None = None,
        using: str | None = None,
        id: int | None = None,
        post: Post | None = None,
        post_id: int | None = None,
        tag: Tag | None = None,
        tag_id: int | None = None,
    ) -> PostTag:
        """Create new object."""
        ...

    async def bulk_create(
        self,
        objects: list[PostTag],
        *,
        batch_size: int | None = None,
        client: Any | None = None,
        using: str | None = None,
    ) -> list[PostTag]:
        """Bulk create objects."""
        ...

    async def bulk_update(
        self,
        objects: list[PostTag],
        fields: list[str],
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Bulk update objects."""
        ...
